import React, { useState } from 'react'
import '../Menu.css'
import Popup from './Popup';
import newMenu01 from '../images/new_menu_01.png'
import newMenu02 from '../images/new_menu_02.png'
import newMenu03 from '../images/new_menu_03.png'
import newMenu04 from '../images/new_menu_04.png'
import newMenu05 from '../images/new_menu_05.png'
import newMenu06 from '../images/new_menu_06.png'
import newMenu07 from '../images/new_menu_07.png'
import newMenu08 from '../images/new_menu_08.png'
import newMenu09 from '../images/new_menu_09.png'
import newMenu10 from '../images/new_menu_10.png'
import newMenu11 from '../images/new_menu_11.png'
import newMenu12 from '../images/new_menu_12.png'
import newMenu13 from '../images/new_menu_13.png'
import newMenu14 from '../images/new_menu_14.png'
import newMenu15 from '../images/new_menu_15.png'
import newMenu16 from '../images/new_menu_16.png'
import newMenu17 from '../images/new_menu_17.png'
import newMenu18 from '../images/new_menu_18.png'
import newMenu19 from '../images/new_menu_19.png'
import newMenu20 from '../images/new_menu_20.png'
import newMenu21 from '../images/new_menu_21.png'
import newMenu22 from '../images/new_menu_22.png'
import newMenu23 from '../images/new_menu_23.png'
import newMenu24 from '../images/new_menu_24.png'
import newMenu25 from '../images/new_menu_25.png'
import newMenu26 from '../images/new_menu_26.png'
import newMenu27 from '../images/new_menu_27.png'
import newMenu28 from '../images/new_menu_28.png'
import newMenu29 from '../images/new_menu_29.png'
import newMenu30 from '../images/new_menu_30.png'
import newMenu31 from '../images/new_menu_31.png'
import newMenu32 from '../images/new_menu_32.png'
import newMenu33 from '../images/new_menu_33.png'
import newMenu34 from '../images/new_menu_34.png'
import newMenu35 from '../images/new_menu_35.png'
import newMenu36 from '../images/new_menu_36.png'
import newMenu37 from '../images/new_menu_37.png'
import newMenu38 from '../images/new_menu_38.png'
import newMenu39 from '../images/new_menu_39.png'
import newMenu40 from '../images/new_menu_40.png'
import newMenu41 from '../images/new_menu_41.png'
import bestSeller01 from '../images/best_seller_01.png'
import bestSeller02 from '../images/best_seller_02.png'
import bestSeller03 from '../images/best_seller_03.png'
import bestSeller04 from '../images/best_seller_04.png'
import bestSeller05 from '../images/best_seller_05.png'
import milkTea01 from '../images/milk_tea_01.png'
import milkTea02 from '../images/milk_tea_02.png'
import milkTea03 from '../images/milk_tea_03.png'
import milkTea04 from '../images/milk_tea_04.png'
import milkTea05 from '../images/milk_tea_05.png'
import milkTea06 from '../images/milk_tea_06.png'
import milkTea07 from '../images/milk_tea_07.png'
import milkTea08 from '../images/milk_tea_08.png'
import milkTea09 from '../images/milk_tea_09.png'
import smoothie01 from '../images/smoothie_01.png'
import smoothie02 from '../images/smoothie_02.png'
import smoothie03 from '../images/smoothie_03.png'
import smoothie04 from '../images/smoothie_04.png'
import smoothie05 from '../images/smoothie_05.png'
import smoothie06 from '../images/smoothie_06.png'
import smoothie07 from '../images/smoothie_07.png'
import smoothie08 from '../images/smoothie_08.png'
import smoothie09 from '../images/smoothie_09.png'
import smoothie10 from '../images/smoothie_10.png'
import smoothie11 from '../images/smoothie_11.png'
import tea01 from '../images/tea_01.png'
import tea02 from '../images/tea_02.png'
import tea03 from '../images/tea_03.png'
import tea04 from '../images/tea_04.png'
import tea05 from '../images/tea_05.png'
import tea06 from '../images/tea_06.png'
import tea07 from '../images/tea_07.png'
import tea08 from '../images/tea_08.png'
import fruitTea01 from '../images/fruit_tea_01.png'
import fruitTea02 from '../images/fruit_tea_02.png'
import fruitTea03 from '../images/fruit_tea_03.png'
import fruitTea04 from '../images/fruit_tea_04.png'
import fruitTea05 from '../images/fruit_tea_05.png'
import fruitTea06 from '../images/fruit_tea_06.png'
import fruitTea07 from '../images/fruit_tea_07.png'
import fruitTea08 from '../images/fruit_tea_08.png'
import fruitTea09 from '../images/fruit_tea_09.png'
import fruitTea10 from '../images/fruit_tea_10.png'
import rtd01 from '../images/rtd_01.png'
import rtd02 from '../images/rtd_02.png'
import rtd03 from '../images/rtd_03.png'
import rtd04 from '../images/rtd_04.png'
import coffee01 from '../images/coffee_01.png'
import coffee02 from '../images/coffee_02.png'
import coffee03 from '../images/coffee_03.png'
import coffee04 from '../images/coffee_04.png'
import coffee05 from '../images/coffee_05.png'

function MenuDrink() {
    const [selectedCategoryBtn, setSelectedCategoryBtn] = useState('NEW 시즌메뉴')
    const [activeCategory, setActiveCategory] = useState('NEW 시즌메뉴'); 
    const [selectedMenu,setSelectedMenu] = useState(null);
    const menuItems = [
        { 
          id: 1, 
          title: '빠다 고구마 크림 밀크티', 
          description: '향긋한 블랙티가 들어간 단짠 솔티드 버터고구마에 고소한 타로폼과 고구마칩을 올려 달콤고소하게 즐기는 시즌한정 밀크티', 
          image: newMenu01, 
          L_price: 'Large 5,100원',
          L_kcal: '281kcal',
          warning: '알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'473ml',
          L_sugar:'24g',
          L_protein:'0g',
          L_fat: '7g',
          L_natrium: '212mg',
          L_caffeine: '28mg',
          J_size:'0',
          J_sugar:'0',
          J_protein:'0',
          J_fat: '0',
          J_natrium: '0',
          J_caffeine: '0',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 2, 
          title: '빠다 고구마 크림 밀크티 + 펄 (HOT)', 
          description: '향긋한 블랙티가 들어간 단짠 솔티드 버터고구마에 쫀득한 펄을 더하여 즐기는 시즌한정 밀크티', 
          image: newMenu01, 
          L_price: 'Large 5,100원',
          L_kcal: '282kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'414ml',
          L_sugar:'21g',
          L_protein:'6g',
          L_fat: '8g',
          L_natrium: '207mg',
          L_caffeine: '28mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 3, 
          title: '빠다 고구마 밀크티 + 펄', 
          description: '향긋한 블랙티가 들어간 단짠 솔티드 버터고구마에 쫀득한 펄을 더하여 즐기는 시즌한정 밀크티', 
          image: newMenu02, 
          L_price: 'Large 5,100원',
          L_kcal: '247kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두, 밀, 이산화황',
          L_size:'473ml',
          L_sugar:'26g',
          L_protein:'5g',
          L_fat: '3g',
          L_natrium: '117mg',
          L_caffeine: '17mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 4, 
          title: '빠다 고구마 밀크티 + 펄 (HOT)', 
          description: '향긋한 블랙티가 들어간 단짠 솔티드 버터고구마에 쫀득한 펄을 더하여 즐기는 시즌한정 밀크티', 
          image: newMenu02, 
          L_price: 'Large 5,100원',
          L_kcal: '247kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두, 밀, 이산화황',
          L_size:'414ml',
          L_sugar:'26g',
          L_protein:'6g',
          L_fat: '3g',
          L_natrium: '128mg',
          L_caffeine: '28mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 5, 
          title: '빠다 고구마 크림 밀크', 
          description: '단짠 솔티드 버터고구마에 고소한 타로폼과 고구마칩을 올려 달콤고소하게 즐기는 시즌한정 밀크', 
          image: newMenu03, 
          L_price: 'Large 5,100원',
          L_kcal: '294kcal',
          warning: '알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'473ml',
          L_sugar:'22g',
          L_protein:'7g',
          L_fat: '9g',
          L_natrium: '204mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 6, 
          title: '빠다 고구마 크림 밀크 (HOT)', 
          description: '단짠 솔티드 버터고구마에 고소한 타로폼과 고구마칩을 올려 달콤고소하게 즐기는 시즌한정 밀크', 
          image: newMenu03, 
          L_price: 'Large 5,100원',
          L_kcal: '283kcal',
          warning: '알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'414ml',
          L_sugar:'21g',
          L_protein:'6g',
          L_fat: '9g',
          L_natrium: '214mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 7, 
          title: '빠다 고구마 크림 스무디', 
          description: '향긋한 블랙티를 더한 단짠 솔티드 버터고구마에 고소한 타로폼과 고구마 칩을 올려 달콤 고소하고 시원하게 즐기는 시즌한정 스무디', 
          image: newMenu04, 
          L_price: 'Large 5,700원',
          L_kcal: '382kcal',
          warning: '알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'473ml',
          L_sugar:'31g',
          L_protein:'1g',
          L_fat: '11g',
          L_natrium: '235mg',
          L_caffeine: '28mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 8, 
          title: '초코바른 피스타치오 스무디', 
          description: '자스민티를 넣은 달콤하고 고소한 피스타치오 스무디에 바삭하게 깨지는 초코바른과 쿠키로 식감을 더한 스무디', 
          image: newMenu05, 
          L_price: 'Large 5,700원',
          L_kcal: '455kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'473ml',
          L_sugar:'38g',
          L_protein:'4g',
          L_fat: '13g',
          L_natrium: '180mg',
          L_caffeine: '21mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 9, 
          title: '초코바른 제주 그린 스무디', 
          description: '제주 녹차로 만든 스무디에 쿠키분태, 달콤짭조름한 치즈폼, 컵에 둘러진 초콜렛으로 비쥬얼을 더한 스무디​', 
          image: newMenu06, 
          L_price: 'Large 5,900원',
          L_kcal: '415kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'473ml',
          L_sugar:'40g',
          L_protein:'3g',
          L_fat: '12g',
          L_natrium: '150mg',
          L_caffeine: '75mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 10, 
          title: '초코바른 초코 스무디', 
          description: '달콤한 초코 쿠키 스무디에 달콤짭조름한 치즈폼, 컵에 둘러진 초콜렛으로 비쥬얼을 더한 스무디', 
          image: newMenu07, 
          L_price: 'Large 5,700원',
          L_kcal: '480kcal',
          warning: '알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'473ml',
          L_sugar:'26g',
          L_protein:'4g',
          L_fat: '18g',
          L_natrium: '180mg',
          L_caffeine: '15mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 11, 
          title: '피스타치오 밀크티 + 펄', 
          description: '자스민티를 넣은 달콤하고 고소한 피스타치오 밀크티에 쫀득쫀득한 펄을 더한 밀크티', 
          image: newMenu08, 
          L_price: 'Large 5,100원',
          J_price: 'Jumbo 6,200원',
          L_kcal: '320kcal',
          J_kcal: '435kcal',
          warning: '알레르기 유발 식품 : 우유, 대두, 이산화황',
          L_size:'473ml',
          L_sugar:'28g',
          L_protein:'8g',
          L_fat: '6g',
          L_natrium: '150mg',
          L_caffeine: '17mg',
          J_size:'651ml',
          J_sugar:'38g',
          J_protein:'11g',
          J_fat: '8g',
          J_natrium: '200mg',
          J_caffeine: '21ml',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
       
        { 
          id: 12, 
          title: '피스타치오 밀크티 + 펄 (HOT)', 
          description: '자스민티를 넣은 달콤하고 고소한 피스타치오 밀크티에 쫀득쫀득한 펄을 더한 밀크티', 
          image: newMenu08, 
          L_price: 'Large 5,700원',
          J_price: 'Jumbo 5,900원',
          L_kcal: '355kcal',
          J_kcal: '460kcal',
          warning: '알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'414ml',
          L_sugar:'35g',
          L_protein:'9g',
          L_fat: '6g',
          L_natrium: '170mg',
          L_caffeine: '17mg',
          J_size:'473ml',
          J_sugar:'45g',
          J_protein:'12g',
          J_fat: '8g',
          J_natrium: '220mg',
          J_caffeine: '21ml',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 13, 
          title: '파인애플 코코넛 스무디', 
          description: '달콤하고 상큼한 파인패션에 고소하고 부드러운 코코넛 밀크 스무디가 들어가 한여름의 하모니를 느낄 수 있는 시즌 한정 제품', 
          image: newMenu09, 
          L_price: 'Large 5,500원',
          L_kcal: '343kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'39g',
          L_protein:'1g',
          L_fat: '8g',
          L_natrium: '97mg',
          L_caffeine: '17.1mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 14, 
          title: '파인애플 오아시스', 
          description: '리얼 파인애플 칩이 통째로! 시원하고 고소한 코코넛 워터가 가득! 무더운 여름철 시원하고 가볍게 즐길 수 있는 카페인 프리 시즌 한정 제품', 
          image: newMenu10, 
          J_price: 'Jumbo 5,700원',
          J_kcal: '155kcal',
          J_size:'651ml',
          J_sugar:'28g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '47mg',
          J_caffeine: '0mg',
          isLargeAvailable: false,
          isJumboAvailable: true
        },
        { 
          id: 15, 
          title: '파인애플 오아시스 티', 
          description: '리얼 파인애플 칩이 통째로! 향긋한 자스민티와 시원하고 고소한 코코넛 워터가 가득! 무더운 여름철 시원하고 가볍게 즐길 수 있는 시즌 한정 제품', 
          image: newMenu11, 
          J_price: 'Jumbo 5,500원',
          J_kcal: '126kcal',
          J_size:'414ml',
          J_sugar:'26g',
          J_protein:'6g',
          J_fat: '3g',
          J_natrium: '128mg',
          J_caffeine: '28mg',
          isLargeAvailable: false,
          isJumboAvailable: true
        },
        { 
          id: 16, 
          title: '코코넛 밀크 스무디 + 펄', 
          description: '고소하고 부드러운 코코넛 밀크 스무디에 쫀득한 펄이 들어가 여름철 시원하게 즐길 수 있는 카페인 프리 시즌 한정 제품', 
          image: newMenu12, 
          L_price: 'Large 5,500원',
          L_kcal: '329kcal',
          warning: '* 알레르기 유발 식품 : 우유, 이산화황',
          L_size:'473ml',
          L_sugar:'32g',
          L_protein:'1g',
          L_fat: '8g',
          L_natrium: '94mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 17, 
          title: '코코넛 블랙 밀크티', 
          description: '고소하고 부드러운 코코넛 밀크에 진한 블랙티가 들어가 여름철 시원하게 즐길 수 있는 시즌 한정 제품', 
          image: newMenu13, 
          L_price: 'Large 4,900원',
          L_kcal: '166kcal',
          warning: '알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'15g',
          L_protein:'4g',
          L_fat: '4g',
          L_natrium: '66mg',
          L_caffeine: '28mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 18, 
          title: '코코넛 밀크 + 미니펄', 
          description: '고소하고 부드러운 코코넛 밀크에 말랑하고 쫀득한 미니펄이 들어간 카페인 프리 시즌 한정 제품', 
          image: newMenu14, 
          L_price: 'Large 5,100원',
          L_kcal: '235kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'21g',
          L_protein:'6g',
          L_fat: '5g',
          L_natrium: '82mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 19, 
          title: '납작 복숭아 아이스티 블랙 + 샷 J', 
          description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 에스프레소 샷과 함께 달콥 쌉싸름 시원하게 즐기는 공차 아이스티', 
          image: newMenu15, 
          J_price: 'Jumbo 4,500원',
          J_kcal: '115kcal',
          J_size:'651ml',
          J_sugar:'0g',
          J_protein:'0g',
          J_fat: '0g',
          J_natrium: '3mg',
          J_caffeine: '197mg',
          isLargeAvailable: false,
          isJumboAvailable: true
        },
        { 
          id: 20, 
          title: '납작 복숭아 아이스티 얼그레이 + 샷 J', 
          description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 에스프레소 샷과 함께 달콥 쌉싸름 시원하게 즐기는 공차 아이스티', 
          image: newMenu16, 
          J_price: 'Jumbo 4,500원',
          J_kcal: '119kcal',
          J_size:'651ml',
          J_sugar:'0g',
          J_protein:'0g',
          J_fat: '0g',
          J_natrium: '3mg',
          J_caffeine: '194mg',
          isLargeAvailable: false,
          isJumboAvailable: true
        },
        { 
          id: 21, 
          title: '납작 복숭아 아이스티 블랙 + 미니펄 J', 
          description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 말랑쫀득 미니펄과 함께 시원하게 즐기는 공차 아이스티', 
          image: newMenu17, 
          J_price: 'Jumbo 4,700원',
          J_kcal: '216kcal',
          J_size:'651ml',
          J_sugar:'9g',
          J_protein:'0g',
          J_fat: '0g',
          J_natrium: '9mg',
          J_caffeine: '68mg',
          isLargeAvailable: false,
          isJumboAvailable: true
        },
        { 
          id: 22, 
          title: '납작 복숭아 아이스티 얼그레이 + 미니펄 J', 
          description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 말랑쫀득 미니펄과 함께 시원하게 즐기는 공차 아이스티', 
          image: newMenu18, 
          J_price: 'Jumbo 4,700원',
          J_kcal: '220kcal',
          J_size:'651ml',
          J_sugar:'9g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '10mg',
          J_caffeine: '65mg',
          isLargeAvailable: false,
          isJumboAvailable: true
        },
        { 
          id: 23, 
          title: '납작 복숭아 아이스티 블랙 + 리얼 복숭아 J', 
          description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 리얼 복숭아 원물과 함께 시원하게 즐기는 공차 아이스티', 
          image: newMenu19, 
          J_price: 'Jumbo 4,500원',
          J_kcal: '161kcal',
          J_size:'651ml',
          J_sugar:'9g',
          J_protein:'0g',
          J_fat: '0g',
          J_natrium: '7mg',
          J_caffeine: '68mg',
          isLargeAvailable: false,
          isJumboAvailable: true
        },
        { 
          id: 24, 
          title: '납작 복숭아 아이스티 얼그레이 + 리얼 복숭아 J', 
          description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 리얼 복숭아 원물과 함께 시원하게 즐기는 공차 아이스티', 
          image: newMenu20, 
          J_price: 'Jumbo 4,500원',
          J_kcal: '165kcal',
          J_size:'651ml',
          J_sugar:'9g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '8mg',
          J_caffeine: '65mg',
          isLargeAvailable: false,
          isJumboAvailable: true
        },
        { 
          id: 25, 
          title: '카페 스무디 with 블랙티', 
          description: '부드러운 커피에 은은한 블랙티와 브라운슈가향이 어우러져 공차만의 스타일로 탄생한 메뉴', 
          image: newMenu21, 
          L_price: 'Large 5,200원',
          L_kcal: '259kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'16g',
          L_protein:'2g',
          L_fat: '6g',
          L_natrium: '94mg',
          L_caffeine: '97mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 26, 
          title: '초당 옥수수 밀크티 + 펄', 
          description: '여름철 대표 간식 “초당옥수수”에 공차의 매력적인 펄과 블랙티를 더하여 시원하게 즐기는 시즌 한정 밀크티', 
          image: newMenu22, 
          L_price: 'Large 5,100원',
          L_kcal: '308kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두, 이산화황',
          L_size:'473ml',
          L_sugar:'29g',
          L_protein:'7g',
          L_fat: '4g',
          L_natrium: '182mg',
          L_caffeine: '24mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        {
          id: 27, 
          title: '미니펄 트리플 딸기 크러쉬', 
          description: '딸기를 3배로 왕창 넣어 더욱 풍성해진 미니펄 딸기 크러쉬', 
          image: newMenu23, 
          L_price: '기본 7,100원'
        },
        {
          id: 28, 
          title: '미니펄 더블 딸기 크러쉬', 
          description: '딸기를 2배로 듬뿍 넣어 더욱 풍성해진 미니펄 딸기 크러쉬', 
          image: newMenu24, 
          L_price: '기본 6,400원'
        },
        {
          id: 29, 
          title: '미니펄 트리플 망고 크러쉬', 
          description: '망고를 3배로 왕창 넣어 더욱 풍성해진 미니펄 망고 크러쉬', 
          image: newMenu25, 
          L_price: '기본 7,100원'
        },
        {
          id: 30, 
          title: '미니펄 더블 망고 크러쉬', 
          description: '망고를 2배로 듬뿍 넣어 더욱 풍성해진 미니펄 망고 크러쉬', 
          image: newMenu26, 
          L_price: '기본 6,400원'
        },
        {
          id: 31, 
          title: '미니펄 트리플 딸기 밀크티', 
          description: '딸기를 3배로 왕창 넣어 더욱 풍성해진 미니펄 딸기 밀크티', 
          image: newMenu27, 
          L_price: '기본 6,700원'
        },
        {
          id: 32, 
          title: '미니펄 더블 딸기 밀크티', 
          description: '딸기를 2배로 듬뿍 넣어 더욱 풍성해진 미니펄 딸기 밀크티', 
          image: newMenu28, 
          L_price: '기본 6,000원'
        },
        {
          id: 33, 
          title: '미니펄 트리플 망고 밀크', 
          description: '망고를 3배로 왕창 넣어 더욱 풍성해진 미니펄 망고 밀크', 
          image: newMenu29, 
          L_price: '기본 6,700원'
        },
        {
          id: 34, 
          title: '미니펄 더블 망고 밀크', 
          description: '망고를 2배로 듬뿍 넣어 더욱 풍성해진 미니펄 망고 밀크', 
          image: newMenu30, 
          L_price: '기본 6,000원'
        },
        { 
          id: 35, 
          title: '청포도 크림치즈폼', 
          description: '새콤 달콤한 청포도 음료를 산뜻하고 부드러운 크림치즈폼과 함께 시원하게 무더운 여름철에 즐길 수 있는 프룻티', 
          image: newMenu31, 
          L_price: 'Large 5,300원',
          L_kcal: '322kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'40g',
          L_protein:'1g',
          L_fat: '7g',
          L_natrium: '170mg',
          L_caffeine: '24mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 36, 
          title: '블랙 사파이어 포도 크림치즈폼', 
          description: '달콤하게 즐길 수있는 블랙사파이어 음료를 산뜻하고 부드러운 크림치즈폼과 함께 시원하게 무더운 여름철에 즐길 수 있는 프룻티', 
          image: newMenu32, 
          L_price: 'Large 5,300원',
          L_kcal: '305kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'37g',
          L_protein:'1g',
          L_fat: '6g',
          L_natrium: '207mg',
          L_caffeine: '85mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 37, 
          title: '꿀 복숭아 스무디', 
          description: '아삭하게 씹히는 복숭아 원물에 달콤한 꿀과 고소한 우롱티를 더해 특별하게 즐기는 시즌 한정 스무디', 
          image: newMenu33, 
          L_price: 'Large 5,300원',
          L_kcal: '344kcal',
          warning: '* 알레르기 유발 식품 : 우유, 복숭아',
          L_size:'473ml',
          L_sugar:'52g',
          L_protein:'1g',
          L_fat: '4g',
          L_natrium: '66mg',
          L_caffeine: '36mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 38, 
          title: '꿀 복숭아 밀크티', 
          description: '아삭하게 씹히는 복숭아 원물에 달콤한 꿀과 고소한 우롱티를 더해 특별하게 즐기는 시즌 한정 밀크티', 
          image: newMenu34, 
          L_price: 'Large 4,900원',
          L_kcal: '287kcal',
          warning: '* 알레르기 유발 식품 : 우유, 복숭아',
          L_size:'473ml',
          L_sugar:'42g',
          L_protein:'6g',
          L_fat: '3g',
          L_natrium: '67mg',
          L_caffeine: '40mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 39, 
          title: '꿀 복숭아 밀크', 
          description: '아삭하게 씹히는 복숭아 원물을 꿀과 함께 조화롭게 즐기는 카페인 프리 복숭아 라떼', 
          image: newMenu35, 
          L_price: 'Large 4,500원',
          L_kcal: '280kcal',
          warning: '* 알레르기 유발 식품 : 우유, 복숭아',
          L_size:'473ml',
          L_sugar:'33g',
          L_protein:'7g',
          L_fat: '4g',
          L_natrium: '81mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 40, 
          title: '꿀 망고 밀크', 
          description: '달콤한 망고와 꿀을 조화롭게 즐길 수 있는 카페인 프리 망고 라떼', 
          image: newMenu36, 
          L_price: 'Large 4,500원',
          L_kcal: '286kcal',
          warning: '* 알레르기 유발 식품 : 우유, 복숭아',
          L_size:'473ml',
          L_sugar:'36g',
          L_protein:'7g',
          L_fat: '5g',
          L_natrium: '84mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 41, 
          title: '꿀 딸기 밀크', 
          description: '상큼한 딸기와 달콤한 꿀을 조화롭게 즐길 수있는 카페인 프리 딸기 라떼', 
          image: newMenu37, 
          L_price: 'Large 4,500원',
          L_kcal: '282kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'35g',
          L_protein:'7g',
          L_fat: '5g',
          L_natrium: '75mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 42, 
          title: '미니펄 망고 밀크', 
          description: '신선한 코코넛 밀크에 달콤한 애플 망고와 쫄깃한 코코넛젤리,쫀득한 미니펄까지 더해 풍성하게 즐기는 시즌 한정 음료', 
          image: newMenu38, 
          L_price: 'Large 5,300원',
          L_kcal: '271kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'26g',
          L_protein:'7g',
          L_fat: '6g',
          L_natrium: '77mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 43, 
          title: '미니펄 딸기 밀크티', 
          description: '신선한 코코넛 밀크에 향긋한 얼그레이티를 블렌딩하고 상큼한 딸기 슬라이스와 쫄깃한 코코넛젤리,쫀득한 미니펄까지 더해 풍성하게 즐기는 시즌 한정 음료', 
          image: newMenu39, 
          L_price: 'Large 5,300원',
          L_kcal: '258kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'31g',
          L_protein:'4g',
          L_fat: '4g',
          L_natrium: '53mg',
          L_caffeine: '44mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 44, 
          title: '미니펄 망고 크러쉬', 
          description: '신선한 코코넛 크러쉬에 달콤한 애플 망고와쫀득한 미니펄을 더해 특별하게 즐기는 시즌 한정 음료', 
          image: newMenu41, 
          L_price: 'Large 5,700원',
          L_kcal: '373kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'34g',
          L_protein:'1g',
          L_fat: '9g',
          L_natrium: '94mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 45, 
          title: '미니펄 딸기 크러쉬', 
          description: '신선한 코코넛 크러쉬에 상큼한 딸기 슬라이스와 딸기 시럽, 쫀득한 미니펄을 더해 특별하게 즐기는 시즌 한정 음료', 
          image: newMenu40, 
          L_price: 'Large 5,700원',
          L_kcal: '386kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'41g',
          L_protein:'1g',
          L_fat: '9g',
          L_natrium: '96mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 46, 
          title: '우롱티 + 코코넛 + 밀크폼', 
          description: '깊고 고소한 우롱차에 코코넛 젤리와 달콤짭쪼름한 밀크폼을 올려 다양한 식감과 함께 부드럽게 즐기는 오리지널티', 
          image: bestSeller01, 
          L_price: 'Large 4,700원',
          J_price: 'Jumbo 6,100원',
          L_kcal: '145kcal',
          J_kcal: '201kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'12g',
          L_protein:'1g',
          L_fat: '6g',
          L_natrium: '136mg',
          L_caffeine: '65mg',
          J_size:'651ml',
          J_sugar:'18g',
          J_protein:'1g',
          J_fat: '7g',
          J_natrium: '181mg',
          J_caffeine: '86ml',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 47, 
          title: '우롱티 + 코코넛 + 밀크폼 (HOT)', 
          description: '깊고 고소한 우롱차에 코코넛 젤리와 달콤짭쪼름한 밀크폼을 올려 다양한 식감과 함께 부드럽게 즐기는 오리지널티', 
          image: bestSeller01, 
          L_price: 'Large 4,700원',
          J_price: 'Jumbo 6,100원',
          L_kcal: '145kcal',
          J_kcal: '201kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'413ml',
          L_sugar:'12g',
          L_protein:'1g',
          L_fat: '6g',
          L_natrium: '138mg',
          L_caffeine: '78mg',
          J_size:'473ml',
          J_sugar:'18g',
          J_protein:'1g',
          J_fat: '7g',
          J_natrium: '184mg',
          J_caffeine: '99ml',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 48, 
          title: '초콜렛 밀크티 + 밀크폼', 
          description: '부드러운 밀크에 녹아든 진한 초콜렛을 느낄 수 있는 초콜렛 밀크티와 달콤짭쪼름한 밀크폼', 
          image: bestSeller02, 
          L_price: 'Large 4,700원',
          J_price: 'Jumbo 5,900원',
          L_kcal: '341kcal',
          J_kcal: '435kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'2g',
          L_protein:'5g',
          L_fat: '16g',
          L_natrium: '183mg',
          L_caffeine: '12mg',
          J_size:'414ml',
          J_sugar:'2g',
          J_protein:'7g',
          J_fat: '20g',
          J_natrium: '201mg',
          J_caffeine: '17ml',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 49, 
          title: '초콜렛 밀크티 + 밀크폼 (HOT)', 
          description: '부드러운 밀크에 녹아든 진한 초콜렛을 느낄 수 있는 초콜렛 밀크티와 달콤짭쪼름한 밀크폼', 
          image: bestSeller02, 
          L_price: 'Large 4,700원',
          J_price: 'Jumbo 6,100원',
          L_kcal: '435kcal',
          J_kcal: '484kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'414ml',
          L_sugar:'2g',
          L_protein:'7g',
          L_fat: '20g',
          L_natrium: '202mg',
          L_caffeine: '16mg',
          J_size:'473ml',
          J_sugar:'2g',
          J_protein:'7g',
          J_fat: '22g',
          J_natrium: '212mg',
          J_caffeine: '19ml',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 50, 
          title: '블랙 밀크티 + 펄', 
          description: '공차 대표 메뉴 블랙밀크티와 쫄깃쫄깃한 펄의 콤비네이션', 
          image: bestSeller03, 
          L_price: 'Large 4,700원',
          J_price: 'Jumbo 5,900원',
          L_kcal: '277kcal',
          J_kcal: '378kcal',
          warning: '* 알레르기 유발 식품 : 우유, 이산화황',
          L_size:'473ml',
          L_sugar:'7g',
          L_protein:'1g',
          L_fat: '9g',
          L_natrium: '59mg',
          L_caffeine: '107mg',
          J_size:'651ml',
          J_sugar:'10g',
          J_protein:'2g',
          J_fat: '13g',
          J_natrium: '81mg',
          J_caffeine: '147ml',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 51, 
          title: '블랙 밀크티 + 펄 (HOT)', 
          description: '공차 대표 메뉴 블랙밀크티와 쫄깃쫄깃한 펄의 콤비네이션', 
          image: bestSeller03, 
          L_price: 'Large 4,700원',
          J_price: 'Jumbo 5,900원',
          L_kcal: '202kcal',
          J_kcal: '246kcal',
          warning: '* 알레르기 유발 식품 : 우유, 이산화황',
          L_size:'414ml',
          L_sugar:'9g',
          L_protein:'6g',
          L_fat: '4g',
          L_natrium: '72mg',
          L_caffeine: '104mg',
          J_size:'651ml',
          J_sugar:'11g',
          J_protein:'7g',
          J_fat: '4.6g',
          J_natrium: '83mg',
          J_caffeine: '118ml',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 52, 
          title: '망고 요구르트 + 화이트펄', 
          description: '달콤한 망고 과육과 요구르트에 화이트펄의 꼬들꼬들함이 느껴지는 주스', 
          image: bestSeller04, 
          L_price: 'Large 5,200원',
          J_price: 'Jumbo 5,900원',
          L_kcal: '202kcal',
          J_kcal: '289kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'40g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '33mg',
          L_caffeine: '0mg',
          J_size:'651ml',
          J_sugar:'57g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '46mg',
          J_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 53, 
          title: '딸기 쿠키 스무디 + 펄', 
          description: '얼그레이티로 만든 밀크 스무디에 달콤한 딸기와 바삭한 쿠키를 더한 스무디와 쫄깃쫄깃한 펄', 
          image: bestSeller05, 
          L_price: 'Large 5,900원',
          L_kcal: '528kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두, 밀, 이산화황',
          L_size:'473ml',
          L_sugar:'60g',
          L_protein:'4g',
          L_fat: '11g',
          L_natrium: '118mg',
          L_caffeine: '21mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 54, 
          title: '블랙 밀크티', 
          description: '진한 향과 맛을 느낄 수 있는 블랙티(홍차)와 밀크의 만남 (HOT / ICED)​', 
          image: milkTea01, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '195kcal',
          J_kcal: '269kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'1g',
          L_protein:'1g',
          L_fat: '9g',
          L_natrium: '53mg',
          L_caffeine: '100mg',
          J_size:'651ml',
          J_sugar:'2g',
          J_protein:'2g',
          J_fat: '13g',
          J_natrium: '73mg',
          J_caffeine: '128mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 55, 
          title: '블랙 밀크티 (HOT)', 
          description: '진한 향과 맛을 느낄 수 있는 블랙티(홍차)와 밀크의 만남 (HOT / ICED)​', 
          image: milkTea01, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '120kcal',
          J_kcal: '137kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'414ml',
          L_sugar:'3g',
          L_protein:'6g',
          L_fat: '4g',
          L_natrium: '65mg',
          L_caffeine: '84mg',
          J_size:'473ml',
          J_sugar:'4g',
          J_protein:'7g',
          J_fat: '4.6g',
          J_natrium: '75mg',
          J_caffeine: '95mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 56, 
          title: '얼그레이 밀크티', 
          description: '베르가못 향의 얼그레이티(홍차)와 밀크가 부드러운 조화를 이루는 밀크티 (HOT / ICED)​', 
          image: milkTea02, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '198kcal',
          J_kcal: '272kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'1g',
          L_protein:'1g',
          L_fat: '10g',
          L_natrium: '50mg',
          L_caffeine: '116mg',
          J_size:'651ml',
          J_sugar:'2g',
          J_protein:'2g',
          J_fat: '13g',
          J_natrium: '68mg',
          J_caffeine: '148mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 57, 
          title: '얼그레이 밀크티 (HOT)', 
          description: '베르가못 향의 얼그레이티(홍차)와 밀크가 부드러운 조화를 이루는 밀크티 (HOT / ICED)​', 
          image: milkTea02, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '198kcal',
          J_kcal: '272kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'414ml',
          L_sugar:'2g',
          L_protein:'5g',
          L_fat: '3.4g',
          L_natrium: '58mg',
          L_caffeine: '97mg',
          J_size:'473ml',
          J_sugar:'3g',
          J_protein:'6g',
          J_fat: '3.9g',
          J_natrium: '67mg',
          J_caffeine: '110mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 58, 
          title: '우롱 밀크티', 
          description: '묵직하고 깊은 향의 우롱차에 밀크가 더해진 우롱밀크티 (HOT / ICED)​', 
          image: milkTea03, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '154kcal',
          J_kcal: '212kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'1g',
          L_protein:'1g',
          L_fat: '8g',
          L_natrium: '38mg',
          L_caffeine: '78mg',
          J_size:'651ml',
          J_sugar:'1g',
          J_protein:'1g',
          J_fat: '11g',
          J_natrium: '52mg',
          J_caffeine: '99mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 59, 
          title: '우롱 밀크티 (HOT)', 
          description: '묵직하고 깊은 향의 우롱차에 밀크가 더해진 우롱밀크티 (HOT / ICED)​', 
          image: milkTea03, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '106kcal',
          J_kcal: '121kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'414ml',
          L_sugar:'2g',
          L_protein:'5g',
          L_fat: '3.5g',
          L_natrium: '59mg',
          L_caffeine: '65mg',
          J_size:'473ml',
          J_sugar:'3g',
          J_protein:'6g',
          J_fat: '4g',
          J_natrium: '67mg',
          J_caffeine: '73mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 60, 
          title: '초콜렛 밀크티', 
          description: '부드러운 밀크에 녹아든 진한 초콜렛을 느낄 수 있는 초콜렛 밀크티 (HOT / ICED)', 
          image: milkTea04, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '249kcal',
          J_kcal: '343kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'1g',
          L_protein:'4g',
          L_fat: '11g',
          L_natrium: '49mg',
          L_caffeine: '12mg',
          J_size:'651ml',
          J_sugar:'1g',
          J_protein:'6g',
          J_fat: '15g',
          J_natrium: '67mg',
          J_caffeine: '17mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 61, 
          title: '초콜렛 밀크티 (HOT)', 
          description: '부드러운 밀크에 녹아든 진한 초콜렛을 느낄 수 있는 초콜렛 밀크티 (HOT / ICED)', 
          image: milkTea04, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '343kcal',
          J_kcal: '392kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'414ml',
          L_sugar:'1g',
          L_protein:'6g',
          L_fat: '15g',
          L_natrium: '67mg',
          L_caffeine: '16mg',
          J_size:'473ml',
          J_sugar:'2g',
          J_protein:'7g',
          J_fat: '17g',
          J_natrium: '77mg',
          J_caffeine: '19mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 62, 
          title: '자스민 밀크티', 
          description: '향긋한 꽃 향이 느껴지는 자스민티를 부드럽게 즐기는 밀크티', 
          image: milkTea05, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '183kcal',
          J_kcal: '252kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'1g',
          L_protein:'1g',
          L_fat: '9g',
          L_natrium: '45mg',
          L_caffeine: '97mg',
          J_size:'651ml',
          J_sugar:'1g',
          J_protein:'2g',
          J_fat: '12g',
          J_natrium: '62mg',
          J_caffeine: '124mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 63, 
          title: '자스민 밀크티 (HOT)', 
          description: '향긋한 꽃 향이 느껴지는 자스민티를 부드럽게 즐기는 밀크티', 
          image: milkTea05, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '107kcal',
          J_kcal: '122kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'414ml',
          L_sugar:'3g',
          L_protein:'5g',
          L_fat: '3.1g',
          L_natrium: '57mg',
          L_caffeine: '81mg',
          J_size:'473ml',
          J_sugar:'3g',
          J_protein:'6g',
          J_fat: '3.6g',
          J_natrium: '65mg',
          J_caffeine: '92mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 64, 
          title: '타로 밀크티', 
          description: '타로의 고소함과 밀크의 조합 (HOT / ICED)​', 
          image: milkTea06, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '297kcal',
          J_kcal: '408kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'6g',
          L_protein:'1g',
          L_fat: '12g',
          L_natrium: '71mg',
          L_caffeine: '0mg',
          J_size:'651ml',
          J_sugar:'9g',
          J_protein:'2g',
          J_fat: '17g',
          J_natrium: '97mg',
          J_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 65, 
          title: '타로 밀크티 (HOT)', 
          description: '타로의 고소함과 밀크의 조합 (HOT / ICED)​', 
          image: milkTea06, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '394kcal',
          J_kcal: '450kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'414ml',
          L_sugar:'9g',
          L_protein:'1g',
          L_fat: '17g',
          L_natrium: '94mg',
          L_caffeine: '0mg',
          J_size:'473ml',
          J_sugar:'10g',
          J_protein:'2g',
          J_fat: '19g',
          J_natrium: '107mg',
          J_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 66, 
          title: '제주 그린 밀크티', 
          description: '제주 녹차를 사용하여 쌉싸름한 맛과 달콤한 맛이 어우러진 밀크티', 
          image: milkTea07, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '184kcal',
          J_kcal: '254kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'16g',
          L_protein:'7g',
          L_fat: '4g',
          L_natrium: '83mg',
          L_caffeine: '49mg',
          J_size:'651ml',
          J_sugar:'22g',
          J_protein:'10g',
          J_fat: '6g',
          J_natrium: '114mg',
          J_caffeine: '67mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 67, 
          title: '제주 그린 밀크티 (HOT)', 
          description: '제주 녹차를 사용하여 쌉싸름한 맛과 달콤한 맛이 어우러진 밀크티', 
          image: milkTea07, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '294kcal',
          J_kcal: '336kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'414ml',
          L_sugar:'25g',
          L_protein:'12g',
          L_fat: '7g',
          L_natrium: '141mg',
          L_caffeine: '62mg',
          J_size:'473ml',
          J_sugar:'29g',
          J_protein:'14g',
          J_fat: '8g',
          J_natrium: '162mg',
          J_caffeine: '71mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 68, 
          title: '브라운슈가 쥬얼리 밀크티', 
          description: '부드럽고 달콤한 브라운 슈가 쥬얼리와 신선한 우유의 맛이 느껴지는 밀크티', 
          image: milkTea08, 
          L_price: 'Large 5,500원',
          L_kcal: '327kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'37g',
          L_protein:'7g',
          L_fat: '7g',
          L_natrium: '160mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 69, 
          title: '브라운슈가 쥬얼리 밀크티 (HOT)', 
          description: '부드럽고 달콤한 브라운 슈가 쥬얼리와 신선한 우유의 맛이 느껴지는 밀크티', 
          image: milkTea08, 
          L_price: 'Large 5,500원',
          L_kcal: '435kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'41g',
          L_protein:'11g',
          L_fat: '10g',
          L_natrium: '204mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 70, 
          title: '딸기 쥬얼리 밀크티', 
          description: '얼그레이티로 만든 밀크티에 리얼 딸기 과즙이 함유된 새콤달콤한 딸기 쥬얼리를 더한 음료 (딸기 함량 UP!) (ONLY ICED)', 
          image: milkTea09, 
          L_price: 'Large 5,300원',
          L_kcal: '225kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'29g',
          L_protein:'5g',
          L_fat: '3.2g',
          L_natrium: '68mg',
          L_caffeine: '13mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 71, 
          title: '밀크 쿠앤크 스무디', 
          description: '달콤하고 바삭한 쿠키가 가득 들어간 밀크 스무디', 
          image: smoothie01, 
          L_price: 'Large 5,300원',
          L_kcal: '389kcal',
          warning: '* 알레르기 유발 식품 : 우유,밀,대두',
          L_size:'473ml',
          L_sugar:'26g',
          L_protein:'2g',
          L_fat: '14g',
          L_natrium: '167mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 72, 
          title: '브라운슈가 쥬얼리 치즈폼 스무디', 
          description: '부드럽고 달콤한 브라운 슈가 쥬얼리와 달콤짭조름한 치즈폼을 더한 스무디', 
          image: smoothie02, 
          L_price: 'Large 5,700원',
          L_kcal: '457kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'45g',
          L_protein:'2g',
          L_fat: '12g',
          L_natrium: '209mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 73, 
          title: '딸기 쿠키 스무디', 
          description: '얼그레이티로 만든 밀크 스무디에 달콤한 딸기와 바삭한 쿠키를 더한 스무디', 
          image: smoothie03, 
          L_price: 'Large 5,700원',
          L_kcal: '446kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'473ml',
          L_sugar:'55g',
          L_protein:'3g',
          L_fat: '11g',
          L_natrium: '111mg',
          L_caffeine: '21mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 74, 
          title: '초코멜로 스무디', 
          description: '깊은 풍미의 초콜렛 스무디', 
          image: smoothie04, 
          L_price: 'Large 5,700원',
          L_kcal: '415kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두, 돼지고기',
          L_size:'473ml',
          L_sugar:'44g',
          L_protein:'5g',
          L_fat: '11g',
          L_natrium: '385mg',
          L_caffeine: '57mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 75, 
          title: '제주 그린 스무디', 
          description: '녹차가루와 부드러운 밀크폼을 함께 즐길 수 있는 제주 그린 스무디', 
          image: smoothie05, 
          L_price: 'Large 5,700원',
          L_kcal: '406kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'40g',
          L_protein:'3g',
          L_fat: '13g',
          L_natrium: '265mg',
          L_caffeine: '88mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 76, 
          title: '청포도 스무디', 
          description: '시원달콤한 청포도과즙과 알로에 알갱이가 쏙쏙 들어오는 재미가 일품인 청포도 스무디', 
          image: smoothie06, 
          L_price: 'Large 5,700원',
          L_kcal: '255kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'50g',
          L_protein:'0g',
          L_fat: '0g',
          L_natrium: '11mg',
          L_caffeine: '10mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 77, 
          title: '망고 스무디', 
          description: '농축된 달콤한 망고와 밀크를 함께 갈아만든 망고 스무디(ONLY ICED)', 
          image: smoothie07, 
          L_price: 'Large 5,700원',
          L_kcal: '321kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'45g',
          L_protein:'1g',
          L_fat: '6g',
          L_natrium: '64mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 78, 
          title: '초콜렛 쿠키&크림 스무디', 
          description: '진한 초코 스무디에 바삭한 쿠키와 밀크폼이 더해진 스무디', 
          image: smoothie08, 
          L_price: 'Large 5,300원',
          L_kcal: '406kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두, 밀',
          L_size:'473ml',
          L_sugar:'17g',
          L_protein:'4g',
          L_fat: '16g',
          L_natrium: '168mg',
          L_caffeine: '28mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 79, 
          title: '딸기 쥬얼리 요구르트 크러쉬', 
          description: '얼그레이티를 넣어 만든 요구르트 크러쉬에 리얼 딸기 과즙이 함유된 새콤달콤한 딸기 쥬얼리를 더한 음료 (ONLY ICED)', 
          image: smoothie09, 
          L_price: 'Large 5,700원',
          L_kcal: '338kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'59g',
          L_protein:'3g',
          L_fat: '1.9g',
          L_natrium: '77mg',
          L_caffeine: '8mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 80, 
          title: '타로 스무디', 
          description: '고소한 타로가 듬뿍 들어가 진하고 달콤하게 즐길 수 있는 시즌 컴백 한정 음료', 
          image: smoothie10, 
          L_price: 'Large 4,800원',
          L_kcal: '337kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'28g',
          L_protein:'1g',
          L_fat: '10g',
          L_natrium: '77mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 81, 
          title: '레몬 요구르트 스무디', 
          description: '상큼한 레몬 베이스에 달콤한 요구르트가 함께 어우려져 시원하게 즐길 수 있는 시즌 컴백 한정 음료', 
          image: smoothie11, 
          L_price: 'Large 4,800원',
          L_kcal: '294kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'50g',
          L_protein:'2g',
          L_fat: '1g',
          L_natrium: '76mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 82, 
          title: '자스민티', 
          description: '향긋한 꽃향이 느껴지는 싱그럽고 부드러운 자스민티', 
          image: tea01, 
          L_price: 'Large 4,000원',
          J_price: 'Jumbo 5,100원',
          L_kcal: '9kcal',
          J_kcal: '12kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'0g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '1mg',
          L_caffeine: '81mg',
          J_size:'473ml',
          J_sugar:'0g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '2mg',
          J_caffeine: '108mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 83, 
          title: '자스민티 (HOT)', 
          description: '향긋한 꽃향이 느껴지는 싱그럽고 부드러운 자스민티', 
          image: tea01, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '7kcal',
          J_kcal: '9kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'0g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '3mg',
          L_caffeine: '97mg',
          J_size:'473ml',
          J_sugar:'0g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '4mg',
          J_caffeine: '124mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 84, 
          title: '블랙티', 
          description: '진한 향과 감미로운 맛을 느낄 수있는 대표적인 홍차, 블랙티 (HOT / ICED)​', 
          image: tea02, 
          L_price: 'Large 4,000원',
          J_price: 'Jumbo 5,100원',
          L_kcal: '8kcal',
          J_kcal: '11kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'0g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '1mg',
          L_caffeine: '84mg',
          J_size:'473ml',
          J_sugar:'0g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '2mg',
          J_caffeine: '112mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 85, 
          title: '블랙티 (HOT)', 
          description: '진한 향과 감미로운 맛을 느낄 수있는 대표적인 홍차, 블랙티 (HOT / ICED)​', 
          image: tea02, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '8kcal',
          J_kcal: '9kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'0g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '4mg',
          L_caffeine: '100mg',
          J_size:'473ml',
          J_sugar:'0g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '4mg',
          J_caffeine: '128mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 86, 
          title: '블랙 스파클링 티', 
          description: '탄산이 톡톡! 청량한 탄산으로 색다르게 즐기는 진하고 감미로운 향의 블랙 스파클링 티', 
          image: tea03, 
          L_price: 'Large 5,700원',
          L_kcal: '1kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'0g',
          L_protein:'0g',
          L_fat: '0g',
          L_natrium: '3mg',
          L_caffeine: '61mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 87, 
          title: '얼그레이티', 
          description: '향긋한 베르가못향이 가미된 얼그레이티 (HOT / ICED)​', 
          image: tea04, 
          L_price: 'Large 4,000원',
          J_price: 'Jumbo 5,100원',
          L_kcal: '8kcal',
          J_kcal: '11kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'0g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '1mg',
          L_caffeine: '97mg',
          J_size:'473ml',
          J_sugar:'0g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '2mg',
          J_caffeine: '129mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 88, 
          title: '얼그레이티 (HOT)', 
          description: '향긋한 베르가못향이 가미된 얼그레이티 (HOT / ICED)​', 
          image: tea04, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '8kcal',
          J_kcal: '9kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'0g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '3mg',
          L_caffeine: '116mg',
          J_size:'473ml',
          J_sugar:'0g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '4mg',
          J_caffeine: '148mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 89, 
          title: '얼그레이 스파클링 티', 
          description: '탄산이 톡톡! 청량한 탄산으로 색다르게 즐기는 향긋한 베르가못 향 얼그레이 스파클링 티', 
          image: tea05, 
          L_price: 'Large 4,300원',
          L_kcal: '1kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'0g',
          L_protein:'0g',
          L_fat: '0g',
          L_natrium: '3mg',
          L_caffeine: '45mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 90, 
          title: '우롱티', 
          description: '묵직하고 깊은 향을 간직한 고소한 우롱차 (HOT / ICED)​', 
          image: tea06, 
          L_price: 'Large 4,000원',
          J_price: 'Jumbo 5,100원',
          L_kcal: '5kcal',
          J_kcal: '7kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'0g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '1mg',
          L_caffeine: '65mg',
          J_size:'473ml',
          J_sugar:'0g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '2mg',
          J_caffeine: '86mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 91, 
          title: '우롱티 (HOT)', 
          description: '묵직하고 깊은 향을 간직한 고소한 우롱차 (HOT / ICED)​', 
          image: tea06, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '5kcal',
          J_kcal: '5kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'0g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '3mg',
          L_caffeine: '78mg',
          J_size:'473ml',
          J_sugar:'0g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '4mg',
          J_caffeine: '99mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 92, 
          title: '우롱 스파클링 티', 
          description: '탄산이 톡톡! 청량한 탄산으로 색다르게 즐기는 묵직하고 깊은 향의 우롱 스파클링 티', 
          image: tea07, 
          L_price: 'Large 5,700원',
          L_kcal: '1kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'0g',
          L_protein:'0g',
          L_fat: '0g',
          L_natrium: '2mg',
          L_caffeine: '47mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 93, 
          title: '자스민 스파클링 티', 
          description: '향긋한 꽃 향을 그대로 담은 오리지널 수제 스파클링 티', 
          image: tea08, 
          L_price: 'Large 4,300원',
          L_kcal: '2kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'0g',
          L_protein:'0g',
          L_fat: '0g',
          L_natrium: '2mg',
          L_caffeine: '60mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 94, 
          title: '망고 요구르트', 
          description: '농축된 달콤한 망고의 입자와 새콤한 요구르트의 조합, 망고 요구르트', 
          image: fruitTea01, 
          L_price: 'Large 5,000원',
          J_price: 'Jumbo 6,100원',
          L_kcal: '170kcal',
          J_kcal: '234kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'31g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '28mg',
          L_caffeine: '0mg',
          J_size:'651ml',
          J_sugar:'43g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '38mg',
          J_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 95, 
          title: '자몽 요구르트', 
          description: '달콤하고 쌉싸름한 자몽과 새콤한 요구르트의 조합', 
          image: fruitTea02, 
          L_price: 'Large 5,000원',
          J_price: 'Jumbo 6,100원',
          L_kcal: '146kcal',
          J_kcal: '201kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'27g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '21mg',
          L_caffeine: '0mg',
          J_size:'651ml',
          J_sugar:'38g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '29mg',
          J_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 96, 
          title: '망고 주스', 
          description: '농축된 달콤한 망고의 입자가 느껴지는 달콤한 망고 주스', 
          image: fruitTea03, 
          L_price: 'Large 4,600원',
          J_price: 'Jumbo 5,700원',
          L_kcal: '130kcal',
          J_kcal: '179kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'24g',
          L_protein:'0g',
          L_fat: '0g',
          L_natrium: '24mg',
          L_caffeine: '0mg',
          J_size:'651ml',
          J_sugar:'33g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '33mg',
          J_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 97, 
          title: '자스민 요구르트', 
          description: '향긋한 자스민티에 새콤달콤한 요구르트의 조합', 
          image: fruitTea04, 
          L_price: 'Large 5,000원',
          J_price: 'Jumbo 6,100원',
          L_kcal: '145kcal',
          J_kcal: '200kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'29g',
          L_protein:'2g',
          L_fat: '0g',
          L_natrium: '22mg',
          L_caffeine: '139mg',
          J_size:'651ml',
          J_sugar:'40g',
          J_protein:'3g',
          J_fat: '0g',
          J_natrium: '30mg',
          J_caffeine: '171mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 98, 
          title: '레몬 자스민티', 
          description: '상큼한 레몬 베이스와 로즈마리가 만드는 새로운 하모니의 자스민 과일 티', 
          image: fruitTea05, 
          L_price: 'Large 4,800원',
          J_price: 'Jumbo 5,900원',
          L_kcal: '162kcal',
          J_kcal: '223kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'34g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '18mg',
          L_caffeine: '175mg',
          J_size:'651ml',
          J_sugar:'46g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '24mg',
          J_caffeine: '210mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 99, 
          title: '레몬 자스민티 (HOT)', 
          description: '상큼한 레몬 베이스와 로즈마리가 만드는 새로운 하모니의 자스민 과일 티', 
          image: fruitTea05, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '131kcal',
          J_kcal: '149kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'28g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '16mg',
          L_caffeine: '201mg',
          J_size:'473ml',
          J_sugar:'32g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '18mg',
          J_caffeine: '241mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 100, 
          title: '레몬 요구르트', 
          description: '상큼한 레몬 베이스에 새콤달콤한 요구르트의 조합', 
          image: fruitTea06, 
          L_price: 'Large 5,000원',
          J_price: 'Jumbo 6,100원',
          L_kcal: '182kcal',
          J_kcal: '250kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'38g',
          L_protein:'2g',
          L_fat: '0g',
          L_natrium: '19mg',
          L_caffeine: '0mg',
          J_size:'651ml',
          J_sugar:'52g',
          J_protein:'2g',
          J_fat: '0g',
          J_natrium: '26mg',
          J_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 101, 
          title: '자몽 자스민티', 
          description: '달콤하고 쌉싸름한 자몽과 로즈마리가 만드는 새로운 하모니의 자스민 과일 티', 
          image: fruitTea07, 
          L_price: 'Large 4,800원',
          J_price: 'Jumbo 5,900원',
          L_kcal: '58kcal',
          J_kcal: '80kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'11g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '4mg',
          L_caffeine: '64mg',
          J_size:'651ml',
          J_sugar:'15g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '5mg',
          J_caffeine: '85mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 102, 
          title: '자몽 자스민티 (HOT)', 
          description: '달콤하고 쌉싸름한 자몽과 로즈마리가 만드는 새로운 하모니의 자스민 과일 티', 
          image: fruitTea07, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '69kcal',
          J_kcal: '79kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'14g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '32mg',
          L_caffeine: '64mg',
          J_size:'473ml',
          J_sugar:'16g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '36mg',
          J_caffeine: '85mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 103, 
          title: '청포도 자스민티', 
          description: '쌉싸름한 자스민티에 상큼한 청포도 넣어 청량하고 달콤한 자스민 과일 티', 
          image: fruitTea08, 
          L_price: 'Large 4,800원',
          J_price: 'Jumbo 5,900원',
          L_kcal: '137kcal',
          J_kcal: '189kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'28g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '5mg',
          L_caffeine: '64mg',
          J_size:'651ml',
          J_sugar:'38g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '7mg',
          J_caffeine: '85mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 104, 
          title: '청포도 자스민티 (HOT)', 
          description: '쌉싸름한 자스민티에 상큼한 청포도 넣어 청량하고 달콤한 자스민 과일 티', 
          image: fruitTea08, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '109kcal',
          J_kcal: '124kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'22g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '6mg',
          L_caffeine: '64mg',
          J_size:'473ml',
          J_sugar:'25g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '7mg',
          J_caffeine: '85mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 105, 
          title: '패션 프룻 히비스커스', 
          description: '새콤달콤한 패션 프룻&히비스커스의 조화가 돋보이는 카페인 Free 티', 
          image: fruitTea09, 
          L_price: 'Large 4,800원',
          J_price: 'Jumbo 5,900원',
          L_kcal: '106kcal',
          J_kcal: '146kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'20g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '8mg',
          L_caffeine: '0mg',
          J_size:'651ml',
          J_sugar:'27g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '11mg',
          J_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 106, 
          title: '패션 프룻 히비스커스 (HOT)', 
          description: '새콤달콤한 패션 프룻&히비스커스의 조화가 돋보이는 카페인 Free 티', 
          image: fruitTea09, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '106kcal',
          J_kcal: '146kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'20g',
          L_protein:'0g',
          L_fat: '0g',
          L_natrium: '8mg',
          L_caffeine: '0mg',
          J_size:'473ml',
          J_sugar:'27	g',
          J_protein:'0g',
          J_fat: '0g',
          J_natrium: '11mg',
          J_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 107, 
          title: '자몽 주스', 
          description: '달콤하고 쌉싸름한 자몽의 입자가 느껴지는 달콤한 자몽 주스', 
          image: fruitTea10, 
          L_price: 'Large 5,700원',
          L_kcal: '386kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'41g',
          L_protein:'1g',
          L_fat: '9g',
          L_natrium: '96mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 108, 
          title: '공차 망고 주스', 
          description: '달콤하고 진한 망고의 맛을 느낄 수 있는 공차 망고 주스', 
          image: rtd01, 
          L_price: 'Large 5,700원',
          L_kcal: '386kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'41g',
          L_protein:'1g',
          L_fat: '9g',
          L_natrium: '96mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 109, 
          title: '공차 딸기 주스', 
          description: '국내산 딸기가 함유되어 있어 더욱 상큼달콤하게 즐길 수 있는 공차 딸기 주스', 
          image: rtd02, 
          L_price: 'Large 5,700원',
          L_kcal: '386kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'41g',
          L_protein:'1g',
          L_fat: '9g',
          L_natrium: '96mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 110, 
          title: '공차 리치 캐모마일', 
          description: '리치의 달콤함과 캐모마일의 부드러운 향이 조화롭게 어우러진 블렌딩 티', 
          image: rtd03, 
          L_price: 'Large 5,700원',
          L_kcal: '386kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'41g',
          L_protein:'1g',
          L_fat: '9g',
          L_natrium: '96mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 111, 
          title: '공차 트로피컬 히비스커스', 
          description: '열대과일의 달콤함과 히비스커스의 상쾌한 산미가 어우러진 이국적인 블렌딩 티', 
          image: rtd04, 
          L_price: 'Large 5,700원',
          L_kcal: '386kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'41g',
          L_protein:'1g',
          L_fat: '9g',
          L_natrium: '96mg',
          L_caffeine: '0mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        },
        { 
          id: 112, 
          title: '얼그레이 아메리카노', 
          description: '공차 시그니처 블렌딩 원두와 향긋한 얼그레이티의 조화가 좋은 스페셜 커피 메뉴', 
          image: coffee01, 
          L_price: 'Large 4,200원',
          J_price: 'Jumbo 4,700원',
          L_kcal: '13kcal',
          J_kcal: '18kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'20g',
          L_protein:'1g',
          L_fat: '0g',
          L_natrium: '1mg',
          L_caffeine: '143mg',
          J_size:'651ml',
          J_sugar:'27g',
          J_protein:'1g',
          J_fat: '0g',
          J_natrium: '1mg',
          J_caffeine: '220mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 113, 
          title: '얼그레이 아메리카노 (HOT)', 
          description: '공차 시그니처 블렌딩 원두와 향긋한 얼그레이티의 조화가 좋은 스페셜 커피 메뉴', 
          image: coffee01, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '13kcal',
          J_kcal: '15kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'20g',
          L_protein:'0g',
          L_fat: '0g',
          L_natrium: '3mg',
          L_caffeine: '147mg',
          J_size:'473ml',
          J_sugar:'27	g',
          J_protein:'0g',
          J_fat: '0g',
          J_natrium: '3mg',
          J_caffeine: '186mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 114, 
          title: '카페 모카', 
          description: '진한 커피에 공차 초콜렛을 더하고 달콤짭조름한 밀크폼과 함께 즐기는 공차만의 커피 음료', 
          image: coffee02, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '310kcal',
          J_kcal: '426kcal',
          warning: '* 알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'8g',
          L_protein:'9g',
          L_fat: '13g',
          L_natrium: '245mg',
          L_caffeine: '148mg',
          J_size:'651ml',
          J_sugar:'11g',
          J_protein:'12g',
          J_fat: '18g',
          J_natrium: '337mg',
          J_caffeine: '219mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 115, 
          title: '카페 모카 (HOT)', 
          description: '진한 커피에 공차 초콜렛을 더하고 달콤짭조름한 밀크폼과 함께 즐기는 공차만의 커피 음료', 
          image: coffee02, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '422kcal',
          J_kcal: '482kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'12g',
          L_protein:'12g',
          L_fat: '19g',
          L_natrium: '329mg',
          L_caffeine: '165mg',
          J_size:'473ml',
          J_sugar:'13g',
          J_protein:'13g',
          J_fat: '21g',
          J_natrium: '376mg',
          J_caffeine: '200mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 116, 
          title: '아메리카노', 
          description: '브라질, 콜롬비아 외 대표적인 원두 5가지를 블렌딩하여 찾은 최적의 맛', 
          image: coffee03, 
          L_price: 'Large 3,700원',
          J_price: 'Jumbo 4,200원',
          L_kcal: '5kcal',
          J_kcal: '7kcal',
          warning: '',
          L_size:'473ml',
          L_sugar:'0g',
          L_protein:'9g',
          L_fat: '0g',
          L_natrium: '3mg',
          L_caffeine: '102mg',
          J_size:'651ml',
          J_sugar:'0g',
          J_protein:'0g',
          J_fat: '0g',
          J_natrium: '4mg',
          J_caffeine: '185mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 117, 
          title: '아메리카노 (HOT)', 
          description: '브라질, 콜롬비아 외 대표적인 원두 5가지를 블렌딩하여 찾은 최적의 맛', 
          image: coffee03, 
          L_price: 'Large 3,700원',
          J_price: 'Jumbo 4,200원',
          L_kcal: '5kcal',
          J_kcal: '5kcal',
          warning: '',
          L_size:'414ml',
          L_sugar:'0g',
          L_protein:'0g',
          L_fat: '0g',
          L_natrium: '5mg',
          L_caffeine: '119mg',
          J_size:'473ml',
          J_sugar:'0g',
          J_protein:'0g',
          J_fat: '0g',
          J_natrium: '6mg',
          J_caffeine: '209mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 118, 
          title: '카페라떼', 
          description: '진하고 부드러운 공차의 새로운 커피 (HOT / ICED)​', 
          image: coffee04, 
          L_price: 'Large 4,200원',
          J_price: 'Jumbo 5,300원',
          L_kcal: '132kcal',
          J_kcal: '182kcal',
          warning: '*알레르기 유발 식품 : 우유',
          L_size:'473ml',
          L_sugar:'9g',
          L_protein:'7g',
          L_fat: '4.3g',
          L_natrium: '82mg',
          L_caffeine: '78mg',
          J_size:'651ml',
          J_sugar:'12g',
          J_protein:'10g',
          J_fat: '6g',
          J_natrium: '113mg',
          J_caffeine: '199mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 119, 
          title: '카페라떼 (HOT)', 
          description: '진하고 부드러운 공차의 새로운 커피 (HOT / ICED)​', 
          image: coffee04, 
          L_price: 'Large 3,700원',
          J_price: 'Jumbo 4,200원',
          L_kcal: '224kcal',
          J_kcal: '225kcal',
          warning: '*알레르기 유발 식품 : 우유',
          L_size:'414ml',
          L_sugar:'13g',
          L_protein:'11g',
          L_fat: '7g',
          L_natrium: '135mg',
          L_caffeine: '109mg',
          J_size:'473ml',
          J_sugar:'15g',
          J_protein:'13g',
          J_fat: '8g',
          J_natrium: '154mg',
          J_caffeine: '236mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 120, 
          title: '바닐라 카페라떼', 
          description: '진한 커피에 마다가스카르산 바닐라빈이 더해져 달콤하고 깊은 풍미를 느낄 수 있는 공차만의 커피 음료', 
          image: coffee05, 
          L_price: 'Large 4,500원',
          J_price: 'Jumbo 5,600원',
          L_kcal: '232kcal',
          J_kcal: '320kcal',
          warning: '*알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'24g',
          L_protein:'8g',
          L_fat: '5g',
          L_natrium: '99mg',
          L_caffeine: '87mg',
          J_size:'651ml',
          J_sugar:'33g',
          J_protein:'11g',
          J_fat: '7g',
          J_natrium: '136mg',
          J_caffeine: '204mg',
          isLargeAvailable: true,
          isJumboAvailable: true
        },
        { 
          id: 121, 
          title: '공차슈페너', 
          description: '향긋한 얼그레이티를 넣은 공차만의 블렌딩 아메리카노에 달콤짭조름한 밀크폼을 얹은 스페셜 메뉴', 
          image: coffee05, 
          L_price: 'Large 4,300원',
          L_kcal: '149kcal',
          warning: '* 알레르기 유발 식품 : 우유, 대두',
          L_size:'473ml',
          L_sugar:'7g',
          L_protein:'1g',
          L_fat: '6g',
          L_natrium: '106mg',
          L_caffeine: '130mg',
          isLargeAvailable: true,
          isJumboAvailable: false
        }
      ];
    const handleButtonClick = (item) => {
        setSelectedMenu(item)
    }
    const handleClosePopup = () => {
        setSelectedMenu(null);
      };
    const menuSections = [
        { title: 'NEW 시즌메뉴', items: menuItems.slice(0, 45) },  
        { title: '베스트셀러', items: menuItems.slice(45, 53) }, 
        { title: '밀크티', items: menuItems.slice(53, 70) },  
        { title: '스무디', items: menuItems.slice(70, 81) }, 
        { title: '오리지널 티', items: menuItems.slice(81, 93) },  
        { title: '프룻티&모어', items: menuItems.slice(93, 107) }, 
        { title: 'RTD', items: menuItems.slice(107, 111) }, 
        { title: '커피', items: menuItems.slice(111, 121) }
    ];
    const handleCategoryChange = (category) => {
      setSelectedCategoryBtn(category)
      setActiveCategory(category); 
  };
    return(
        <main className='menu'>
          <div className='menu_banner_wrap'>
              <div className='menu_banner'>
                <div className='menu_banner_cont'>
                  <h2>음료</h2>
                  <p>공차의 다양한 음료를 소개합니다.</p>
                </div>
              </div>
          </div>

          <div className='menu_gnb'>
              <ul>
                  <li><button className={selectedCategoryBtn === 'NEW 시즌메뉴' ? 'active' : ''} 
                  onClick={() => handleCategoryChange('NEW 시즌메뉴')}>NEW 시즌메뉴</button></li>
                  <li><button className={selectedCategoryBtn === '베스트셀러' ? 'active' : ''} 
                  onClick={() => handleCategoryChange('베스트셀러')}>베스트셀러</button></li>
                  <li><button className={selectedCategoryBtn === '밀크티' ? 'active' : ''} 
                  onClick={() => handleCategoryChange('밀크티')}>밀크티</button></li>
                  <li><button className={selectedCategoryBtn === '스무디' ? 'active' : ''} 
                  onClick={() => handleCategoryChange('스무디')}>스무디</button></li>
                  <li><button className={selectedCategoryBtn === '오리지널 티' ? 'active' : ''} 
                  onClick={() => handleCategoryChange('오리지널 티')}>오리지널 티</button></li>
                  <li><button className={selectedCategoryBtn === '프룻티&모어' ? 'active' : ''} 
                  onClick={() => handleCategoryChange('프룻티&모어')}>프룻티&모어</button></li>
                  <li><button className={selectedCategoryBtn === 'RTD' ? 'active' : ''} 
                  onClick={() => handleCategoryChange('RTD')}>RTD</button></li>
                  <li><button className={selectedCategoryBtn === '커피' ? 'active' : ''} 
                  onClick={() => handleCategoryChange('커피')}>커피</button></li>
              </ul>
          </div>

          <div className='change_menu_cont'>
              <h3>{activeCategory}</h3>
              {menuSections
                  .filter(section => section.title === activeCategory) 
                  .map((section, index) => (
                      <div key={index} className='menu_cont_01 menu_default'>
                            {section.title === 'NEW 시즌메뉴' && <h4>{section.title}</h4>}
                          <ul>
                              {section.items.map(item => (
                                  <li key={item.id}>
                                      <button onClick={() => handleButtonClick(item)}>
                                          <img src={item.image} alt={item.title} />
                                          <p>{item.title}</p>
                                      </button>
                                  </li>
                              ))}
                          </ul>
                      </div>
                  ))}
          </div>

            {selectedMenu && (
                <Popup content={selectedMenu} onClose={handleClosePopup} />
            )}
        </main>
    )
}
export default MenuDrink;